### ISSUE TITLE
Invalid syntax (rounded_path.py, line 29)

### ISSUE THREAD

**Issue by helman** [viesturz/klipper-toolchanger#30]
Hi @viesturz I'm having issue installing the extension, Klipper complain about syntax error:

![Screenshot 2024-08-16 at 10 58 36 PM](https://github.com/user-attachments/assets/2526a350-341f-42ea-a140-62f06fc4b346)

this is the error log from klipper
```
=======================
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 130, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 123, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 103, in load_object
    mod = importlib.import_module('extras.' + module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/klipper/klippy/extras/rounded_path.py", line 29
    def _vecto(f: ControlPoint, t: ControlPoint)->list:
                ^

```

```bash
pi@mainsailos:~ $ /home/pi/klippy-env/bin/python --version
Python 3.7.3

```

**Comment by helman** [comment]
closing this as it doesn't throw the syntax error anymore after re-create the `klippy-env`
