### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by Neokil** [viesturz/klipper-toolchanger#34]
I just ran into this error:
```
Traceback (most recent call last):
  File "/home/biqu/klipper/klippy/klippy.py", line 130, in _connect
    self._read_config()
  File "/home/biqu/klipper/klippy/klippy.py", line 123, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/biqu/klipper/klippy/klippy.py", line 112, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/biqu/klipper/klippy/extras/tool_probe.py", line 173, in load_config_prefix
    return ToolProbe(config)
  File "/home/biqu/klipper/klippy/extras/tool_probe.py", line 27, in __init__
    self.endstop.add_probe(config, self)
  File "/home/biqu/klipper/klippy/extras/tool_probe_endstop.py", line 66, in add_probe
    raise config.error("Duplicate tool probe nr: " + tool_probe.tool)
TypeError: can only concatenate str (not "int") to str
```
Easy to fix as I forgot to change the "tool" number in the tool-probe config, but I think the code should still be fixed so the correct error message gets shown :)

**Comment by viesturz** [comment]
Thanks, fixed
